# Generated by Django 5.0.6 on 2024-07-01 05:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_leadership_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='commitment',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Funksiyanal majburiyati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadership',
            name='activity',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mehnat faoliyati'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='career',
            field=models.CharField(max_length=250, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='fullname',
            field=models.CharField(max_length=250, verbose_name='F.I.O'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='phone',
            field=models.CharField(max_length=250, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='reception_time',
            field=models.CharField(max_length=250, verbose_name='Qabul vaqti'),
        ),
    ]
