# Generated by Django 5.0.6 on 2024-07-01 07:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_leadership_commitment_alter_leadership_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='activity',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mehnat faoliyati'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='commitment',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiyanal majburiyati'),
        ),
    ]
